# Generated by Django 5.0.6 on 2024-07-21 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0003_author_serie_seriesprivately'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='refs.author'),
        ),
        migrations.AlterField(
            model_name='seriesprivately',
            name='series_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='privately', to='refs.serie'),
        ),
    ]
