# Generated by Django 5.0.6 on 2024-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0005_alter_serie_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='total_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seriesprivately',
            name='book_number',
            field=models.PositiveIntegerField(),
        ),
    ]
