# Generated by Django 5.0.6 on 2024-08-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0008_publishingnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publishingnew',
        ),
    ]
