# Generated by Django 5.0.6 on 2024-08-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0009_delete_publishingnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
