# Generated by Django 5.0.6 on 2024-08-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refs', '0010_delete_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('cover', models.ImageField(upload_to='', verbose_name='Фото обложки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена, BYN')),
                ('publishing_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('binding', models.CharField(blank=True, default='Твердый', max_length=200, null=True, verbose_name='')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('weight', models.PositiveSmallIntegerField(default=15, verbose_name='Вес, гр')),
                ('format', models.CharField(blank=True, default='70x90/16', max_length=100, null=True, verbose_name='Формат')),
                ('age_restrictions', models.CharField(blank=True, max_length=5, null=True, verbose_name='Возрастные ограничения')),
                ('item_in_stock', models.PositiveSmallIntegerField(default=1, verbose_name='Количество книг в наличии')),
                ('active', models.BooleanField(default=True, verbose_name='Достуно для заказа')),
                ('rating', models.PositiveSmallIntegerField(default=1, verbose_name='Рейтинг')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('date_last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('author', models.ManyToManyField(related_name='books', to='refs.author', verbose_name='Автор')),
                ('genre', models.ManyToManyField(related_name='books_in_genre', to='refs.genre', verbose_name='Жанр')),
                ('publishing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_published', to='refs.publishing', verbose_name='Издательство')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_in_seria', to='refs.serie', verbose_name='Название серии')),
            ],
        ),
    ]
