# Generated by Django 5.0.6 on 2024-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='add_inform',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки'),
        ),
    ]
