# Generated by Django 5.0.6 on 2024-09-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_item_cover'),
        ('orders', '0002_cart_created_cart_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price per item')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.cart', verbose_name='Cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_in_cart', to='goods.item', verbose_name='Item')),
            ],
        ),
    ]
