# Generated by Django 5.0.6 on 2024-09-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_itemincart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=15, verbose_name='Telephone')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='orders.cart')),
            ],
        ),
    ]
