# Generated by Django 5.0.6 on 2024-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tel',
        ),
        migrations.AddField(
            model_name='order',
            name='add_inform',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Товар доставить по адресу:', max_length=500, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='+375', max_length=15, verbose_name='Номер телефона'),
        ),
    ]
